### ISSUE TITLE
I always get "Access Denied 403"

### ISSUE THREAD

**Issue by GBeushausen** [Craftware/aws-lambda-unzip#2]
Unfortunatly i always get the error "Access denied 403". Even with this policy file:

`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": "*"
    }
  ]
}`

What can i do about this?

**Comment by gravelg** [comment]
Hi!

I've looked through our configuration and it seems that we no longer use the bucket policy directly. I've created a role that I attach to the lambda on creation. This role has the following inline policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject",
                "s3:DeleteObject"
            ],
            "Resource": [
                "arn:aws:s3:::*"
            ]
        }
    ]
}
```

This allows the lambda to read and write to s3, and to push logs of execution to cloudwatch logs (great for debugging).

Hope this helps!

**Comment by GBeushausen** [comment]
Thanks, that helped. Now it works fine.

One Question: The files always get extracted to the main bucket directory. Is it possible to extract the files to the same directory where the zip was?

For example BUCKET_NAME/images/userploads/user/12344 is where my zip is. Is it possible to extract to that same directory?

**Comment by gravelg** [comment]
You may want to check the 'version_update'  branch on the project. It unzips in place and archives the zip file in a folder. You can probably fork that and remove the archiving if you don't need it.

**Comment by GBeushausen** [comment]
Great. Thanks.
