### ISSUE TITLE
Setting the Metadata value for Extracted files

### ISSUE THREAD

**Issue by Wasca** [Craftware/aws-lambda-unzip#5]
Hello

I have been using this great little tool for a while now and have just noticed that when I upload a zip file that contains images (e.g. png's) the images are extracted correctly by the lambda function however the Metadata for the files is set to Content Type - application/octet-stream. This means when I visit the URL of the image in a browser it is downloaded instead of simply opened in the browser.

How do I set the correct Metadata value of the images when they are extracted by the lambda function?

Thanks :D

**Comment by Wasca** [comment]
Never mind! I just saw your last commit dealt with that very issue. I'll download the new version of your code and see if that fixes it. 

Thanks again

**Comment by gravelg** [comment]
Using the latest version is recommended, however if one of your files has an extension not listed in FileMimeType, feel free to make a pull request for a change.

**Comment by Wasca** [comment]
Hi gravelg

Just did a pull and recompiled the project, uploaded it to lambda and did my first test. Unfortunately newly uploaded zip files with png's were still setting the png files to Content Type - application/octet-stream.

Not sure what to check next.

**Comment by gravelg** [comment]
The lambda will output detailed information about the execution of the unzip, you should find this information in an CloudWatch log bucket I think. You should be able to see the full path for the files and the detected mimetype in that file. Can you post it here?

**Comment by Wasca** [comment]
Hi gravelg

All fixed, it was my lack of understanding in how to update an existing Lambda function. The new code was not being used.

Thanks for your prompt replies and a great little tool!

Cheers
