### ISSUE TITLE
How to uncompress gzip (gz) files?

### ISSUE THREAD

**Issue by ibaralf** [Craftware/aws-lambda-unzip#6]
Any idea how I can apply this to uncompress gzip files (gz)? I tried using the GZIPInputStream class, but not successful.

**Comment by gravelg** [comment]
Hey @ibaralf , sorry I'm not sure I can help on this anymore, we are no longer using this project anymore.

**Comment by ibaralf** [comment]
Now worries, I got it working using `java.util.zip.GZIPInputStream`. I'll close it.
